POST {{api}}/projects
Content-Type: application/json

{
  "name": "Mój drugi projekt"
}

###

POST {{api}}/projects
Content-Type: application/json

{
  "name": "Mój trzeci projekt"
}

###

POST {{api}}/projects
Content-Type: application/json

{
  "name": "Mój czwarty projekt"
}

###

POST {{api}}/projects
Content-Type: application/json

{
  "name": "Mój czwarty projekt"
}

###

GET {{api}}/projects?full=true

###

PUT {{api}}/projects/5
Content-Type: application/json

{
  "name": "Mój piąty test"
}

###

GET {{api}}/projects/

###

GET {{api}}/projects?full=true

###

DELETE {{api}}/projects/2

###

GET {{api}}/projects/

###

GET {{api}}/tasks/

###

PUT {{api}}/projects/1/removeTask
Content-Type: application/json

{
  "taskId": 2
}

###

GET {{api}}/tasks/

###

PUT {{api}}/projects/1/removeTask
Content-Type: application/json

{
  "taskId": 3
}

###

GET {{api}}/projects/
###

GET {{api}}/projects?full=true

###

PUT {{api}}/projects/3/addTask
Content-Type: application/json

{
  "taskId": 2
}

###


GET {{api}}/projects/

###

###

PUT {{api}}/projects/4/addTask
Content-Type: application/json

{
  "taskId": 3
}

###

PUT {{api}}/projects/1/addTask
Content-Type: application/json

{
  "taskId": 1
}

###