POST localhost:9090/api/tasks
Content-Type: application/json

{
  "title": "Pierwszy test",
  "author": "Autor 1",
  "createDateTime": "2019-11-24T12:00:00"
}

###

GET localhost:9090/api/tasks/

###

POST localhost:9090/api/tasks/
Content-Type: application/json

{
  "title": "Drugi test",
  "author": "Autor 2",
  "createDateTime": "2019-11-24T16:00:00"
}

###

###

POST localhost:9090/api/tasks/
Content-Type: application/json

{
  "title": "Trzeci test",
  "author": "Autor 3",
  "createDateTime": "2019-11-25T00:00:00"
}

###

DELETE localhost:9090/api/tasks/1

###

PUT localhost:9090/api/tasks

###

POST localhost:9090/api/tasks/1
Content-Type: application/json

{
"title": "Pierwszy test",
"author": "Autor 1.1",
"description": "Dodanie nowego testu"
}

###
PUT localhost:9090/api/tasks/1
Content-Type: application/json

{
  "title": "Poprawić temat",
  "author": "Autor 1-1",
  "description": "poprawka"
}

###
POST localhost:9090/api/tasks/1/tags
Content-Type: application/json

{
  "tagId": 3
}

###