POST {{api}}/tasks
Content-Type: application/json

{
  "title": "Pierwszy test",
  "author": "Autor 1",
  "createDateTime": "2019-11-24T12:00:00"
}

###

GET {{api}}/tasks/

###

POST {{api}}/tasks/
Content-Type: application/json

{
  "title": "Drugi test",
  "author": "Autor 2",
  "createDateTime": "2019-11-24T16:00:00"
}

###

###

POST {{api}}/tasks/
Content-Type: application/json

{
  "title": "Trzeci test",
  "author": "Autor 3",
  "createDateTime": "2019-11-25T00:00:00"
}

###

DELETE {{api}}/tasks/1

###

PUT {{api}}/tasks

###

POST {{api}}/tasks/1
Content-Type: application/json

{
"title": "Pierwszy test",
"author": "Autor 1.1",
"description": "Dodanie nowego testu"
}

###
PUT {{api}}/tasks/1
Content-Type: application/json

{
  "title": "Poprawić temat",
  "author": "Autor 1-1",
  "description": "poprawka"
}

###
POST {{api}}/tasks/1/tags
Content-Type: application/json

{
  "tagId": 2
}

###

POST {{api}}/tasks/
Content-Type: application/json

{
  "title": "Dokończyć moduł 8",
  "author": "Ja",
  "description" : "Jpa i Hibernate cz.2. ",
  "tags" : ["pilne", "w domu", "telefon"]
}

###

GET {{api}}/tasks/

###