server.port: 9090
app.tasks.endpointMessage: Hello, World!!!
storage.path: D:/opt/works
spring:
  datasource:
    url=jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE:
  h2:
    console:
      enabled: true
logging:
    level:
      org.springframework.jdbc.core: DEBUG
      org.springframework.jdbc.jpa: DEBUG